slack lunch:
  user.switcher_focus("Slack")
  key(cmd-shift-y)
  sleep(100ms)
  key(tab)
  key(enter)
  key(tab)
  key(tab)
  key(tab)
  key(tab)
  key(tab)
  key(tab)
  key(tab)
  key(enter)

slack clear status:
  user.switcher_focus("Slack")
  key(cmd-shift-y)
  sleep(100ms)
  key(tab)
  key(tab)
  key(tab)
  key(enter)